### ISSUE TITLE
Queue fails to drain when something is longer than 255 

### ISSUE THREAD

**Issue by robotdan** [CleanSpeak/cleanspeak-issues#33]
### Description 
The `location`, `receiver_display_name`, or `sender_display_name` is longer than `255`, and then gets stuck in the queue. 

Need to ensure we are validating these lengths prior to adding to the queue. 

```
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO content_items (id, content, create_instant, generated_alert, insert_instant, last_update_user_id,                                location, persistent, receiver_display_name, receiver_id, required_approval,                                sender_display_name, sender_id, was_actioned, was_approved, was_dismissed, was_escalated,                                was_rejected, applications_id) VALUES                  (?, ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?, ?)      ,        (?, ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?, ?)      ,        (?, ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?, ?)      ,        (?, ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?,       ?, ?, ?, ?,       ?, ?, ?, ?)
### Cause: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
        at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:350)
        at com.sun.proxy.$Proxy75.insert(Unknown Source)
        at org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:236)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
        at com.sun.proxy.$Proxy83.createBulk(Unknown Source)
        at com.inversoft.cleanspeak.api.service.content.DefaultContentItemService.createBulk(DefaultContentItemService.java:100)
        at com.inversoft.cleanspeak.api.service.moderation.ContentQueueDrainer.flush(ContentQueueDrainer.java:148)
```

### Related
- https://github.com/CleanSpeak/cleanspeak-issues/issues/32

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]

**Comment by brettwp** [comment]
Fixes for this are in `cleanspeak-webservice` [PR #1](https://github.com/CleanSpeak/cleanspeak-webservice/pull/1).
